### PR TITLE
Feature/streams

### PR DESCRIPTION
**Pull request by jonnyreeves**
WIP implementation of stream-based parsers, see #16.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
cc @ariutta - sorry for the delay; hoping to start getting this nailed down now.  I've gone for a slightly different API for the `parser` basing it on a trimmed down implementation of the `Response` object provided by the `fetch` API.  This will give the parser access to the Headers, statusCode and provide the ability to cancel the response stream (#19)

**Comment by jonnyreeves** [comment]
This branch now incorperate's @jimmywarting's ideas on using a `ReadableStream` polyfill for the xhr-based transports; we can now provide a 'fetch-like' API to the `parser` function.

One question that arises from this change is does providing a parser make sense, or should the library just become a `fetch-binary-stream` which focuses on allowing you to make http requests from the browser for streamed binary data from the server?

**Comment by jimmywarting** [comment]
You are kind of polyfilling the fetch api now? 😆 
Which has already been done: [here](https://github.com/github/fetch/issues/198)
<s>But they don't seem to plan on adding streaming support https://github.com/github/fetch/issues/198 👎 </s>

You should maybe make a PR to them :P

**Comment by jimmywarting** [comment]
I don't think you should parse the arrayBuffer to string. If it's going to work like fetch ReadableStream then parsing the response to text is, well kind of unexpected. The Stream api have something like a binary stream that is more friendly with memory allocation. Other libraries could take advantage of this such as jszip where they could "read into a ArrayBuffer allocation"

The TextDecoder api will eventually have some Transform stream
Then you just have to `.pipeThrogh(new TextDecoder)` something like that

You can create another module that's more like a polyfill out of TextDecoder transform. I almost did it with [web-byline](https://github.com/jimmywarting/web-byline)
You can take out most of the logic from [index.js](https://github.com/jimmywarting/web-byline/blob/master/index.js) and only keep the TextDecoder part

Beside you don't want to parse a binary and you only get one ReadableStream back, so how do you know if you should parse it? you don't want to do it with a image... and it don't look good with an option such as `createReadableStream({parse: boolean})`

Think it's just better to pipe it
So i say remove the parser!

**Comment by jonnyreeves** [comment]
OK - taken a very different approach over the last few days and have pulled the guts of this library out into a new library: https://github.com/jonnyreeves/fetch-readablestream

I am unsure what to do about this library - it feels a touch redundant now as it just provides a defaultParser implementation which is trivial to re-create in user code, eg: https://github.com/jonnyreeves/fetch-readablestream/blob/release/v0.1.0/test/integ/util.js

**Pull request closed without merging**
